export type CoveredRoute = {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  reason: string;
};

export const SRS_CLIENT_FLOW_ROUTES: CoveredRoute[] = [
  { method: 'GET', path: '/health', reason: 'Health check' },
  { method: 'POST', path: '/api/v1/auth/register', reason: 'Registration flow' },
  { method: 'POST', path: '/api/v1/auth/verify-otp', reason: 'Registration flow' },
  { method: 'POST', path: '/api/v1/auth/login', reason: 'Session flow' },
  { method: 'POST', path: '/api/v1/auth/refresh', reason: 'Session flow' },
  { method: 'POST', path: '/api/v1/auth/logout', reason: 'Session flow' },
  { method: 'POST', path: '/api/v1/auth/forgot-password', reason: 'Password recovery flow' },
  { method: 'POST', path: '/api/v1/auth/reset-password', reason: 'Password recovery flow' },
  { method: 'GET', path: '/api/v1/users/me', reason: 'Profile flow' },
  { method: 'PATCH', path: '/api/v1/users/me', reason: 'Profile flow' },
  { method: 'POST', path: '/api/v1/users/me/change-password', reason: 'Profile flow' },
  { method: 'GET', path: '/api/v1/galleryItems', reason: 'Gallery flow' },
  { method: 'GET', path: '/api/v1/galleryItems/:id', reason: 'Gallery flow' },
  { method: 'POST', path: '/api/v1/galleryItems', reason: 'Admin gallery catalog flow' },
  { method: 'PUT', path: '/api/v1/galleryItems/:id', reason: 'Admin gallery catalog flow' },
  { method: 'PATCH', path: '/api/v1/galleryItems/:id', reason: 'Admin gallery catalog flow' },
  { method: 'DELETE', path: '/api/v1/galleryItems/:id', reason: 'Admin gallery catalog flow' },
  { method: 'POST', path: '/api/v1/comments', reason: 'Gallery interaction flow' },
  { method: 'PATCH', path: '/api/v1/comments/:id', reason: 'Gallery interaction flow' },
  { method: 'DELETE', path: '/api/v1/comments/:id', reason: 'Gallery interaction flow' },
  { method: 'POST', path: '/api/v1/reactions', reason: 'Gallery interaction flow' },
  { method: 'PATCH', path: '/api/v1/reactions/:id', reason: 'Gallery interaction flow' },
  { method: 'DELETE', path: '/api/v1/reactions/:id', reason: 'Gallery interaction flow' },
  { method: 'POST', path: '/api/v1/favorites', reason: 'Gallery interaction flow' },
  { method: 'GET', path: '/api/v1/favorites', reason: 'Gallery interaction flow' },
  { method: 'DELETE', path: '/api/v1/favorites/:id', reason: 'Gallery interaction flow' },
  { method: 'GET', path: '/api/v1/units', reason: 'Unit discovery flow' },
  { method: 'GET', path: '/api/v1/units/:id', reason: 'Unit discovery flow' },
  { method: 'POST', path: '/api/v1/bookingRequests', reason: 'Booking flow' },
  { method: 'GET', path: '/api/v1/bookingRequests/me', reason: 'Booking flow' },
  { method: 'GET', path: '/api/v1/bookingRequests/:id', reason: 'Booking flow' },
  { method: 'DELETE', path: '/api/v1/bookingRequests/:id', reason: 'Booking flow' },
  { method: 'GET', path: '/api/v1/bookingRequests', reason: 'Admin booking review flow' },
  { method: 'PATCH', path: '/api/v1/bookingRequests/:id/review', reason: 'Admin booking review flow' },
  { method: 'POST', path: '/api/v1/sellUnitRequests', reason: 'Sell unit flow' },
  { method: 'GET', path: '/api/v1/sellUnitRequests/me', reason: 'Sell unit flow' },
  { method: 'GET', path: '/api/v1/sellUnitRequests/:id', reason: 'Sell unit flow' },
  { method: 'DELETE', path: '/api/v1/sellUnitRequests/:id', reason: 'Sell unit flow' },
  { method: 'GET', path: '/api/v1/sellUnitRequests', reason: 'Admin sell-unit review flow' },
  { method: 'PATCH', path: '/api/v1/sellUnitRequests/:id/review', reason: 'Admin sell-unit review flow' },
  { method: 'POST', path: '/api/v1/unitOrderRequests', reason: 'Unit order flow' },
  { method: 'GET', path: '/api/v1/unitOrderRequests/me', reason: 'Unit order flow' },
  { method: 'GET', path: '/api/v1/unitOrderRequests/:id', reason: 'Unit order flow' },
  { method: 'DELETE', path: '/api/v1/unitOrderRequests/:id', reason: 'Unit order flow' },
  { method: 'GET', path: '/api/v1/unitOrderRequests', reason: 'Admin unit-order review flow' },
  { method: 'PATCH', path: '/api/v1/unitOrderRequests/:id/review', reason: 'Admin unit-order review flow' },
  { method: 'GET', path: '/api/v1/finishes', reason: 'Finish flow' },
  { method: 'GET', path: '/api/v1/finishes/:id', reason: 'Finish flow' },
  { method: 'POST', path: '/api/v1/finishes', reason: 'Admin finish catalog flow' },
  { method: 'PUT', path: '/api/v1/finishes/:id', reason: 'Admin finish catalog flow' },
  { method: 'PATCH', path: '/api/v1/finishes/:id', reason: 'Admin finish catalog flow' },
  { method: 'DELETE', path: '/api/v1/finishes/:id', reason: 'Admin finish catalog flow' },
  { method: 'POST', path: '/api/v1/finishRequests', reason: 'Finish request flow' },
  { method: 'GET', path: '/api/v1/finishRequests/me', reason: 'Finish request flow' },
  { method: 'GET', path: '/api/v1/finishRequests/:id', reason: 'Finish request flow' },
  { method: 'DELETE', path: '/api/v1/finishRequests/:id', reason: 'Finish request flow' },
  { method: 'GET', path: '/api/v1/finishRequests', reason: 'Admin finish review flow' },
  { method: 'PATCH', path: '/api/v1/finishRequests/:id/review', reason: 'Admin finish review flow' },
  { method: 'GET', path: '/api/v1/furnitureItems', reason: 'Furniture flow' },
  { method: 'GET', path: '/api/v1/furnitureItems/:id', reason: 'Furniture flow' },
  { method: 'POST', path: '/api/v1/furnitureItems', reason: 'Admin furniture catalog flow' },
  { method: 'PUT', path: '/api/v1/furnitureItems/:id', reason: 'Admin furniture catalog flow' },
  { method: 'PATCH', path: '/api/v1/furnitureItems/:id', reason: 'Admin furniture catalog flow' },
  { method: 'DELETE', path: '/api/v1/furnitureItems/:id', reason: 'Admin furniture catalog flow' },
  { method: 'POST', path: '/api/v1/furnitureBookings', reason: 'Furniture booking flow' },
  { method: 'GET', path: '/api/v1/furnitureBookings/me', reason: 'Furniture booking flow' },
  { method: 'GET', path: '/api/v1/furnitureBookings/:id', reason: 'Furniture booking flow' },
  { method: 'DELETE', path: '/api/v1/furnitureBookings/:id', reason: 'Furniture booking flow' },
  { method: 'GET', path: '/api/v1/furnitureBookings', reason: 'Admin furniture-booking review flow' },
  { method: 'PATCH', path: '/api/v1/furnitureBookings/:id/review', reason: 'Admin furniture-booking review flow' },
  { method: 'POST', path: '/api/v1/specialFurnitureRequests', reason: 'Special furniture flow' },
  { method: 'GET', path: '/api/v1/specialFurnitureRequests/me', reason: 'Special furniture flow' },
  { method: 'GET', path: '/api/v1/specialFurnitureRequests/:id', reason: 'Special furniture flow' },
  { method: 'DELETE', path: '/api/v1/specialFurnitureRequests/:id', reason: 'Special furniture flow' },
  { method: 'GET', path: '/api/v1/specialFurnitureRequests', reason: 'Admin special-furniture review flow' },
  { method: 'PATCH', path: '/api/v1/specialFurnitureRequests/:id/review', reason: 'Admin special-furniture review flow' },
  { method: 'POST', path: '/api/v1/storage/presigned-url', reason: 'Storage upload flow' },
];

export const SRS_CLIENT_FLOW_ROUTE_KEYS = new Set(
  SRS_CLIENT_FLOW_ROUTES.map((route) => `${route.method} ${route.path}`)
);
